using mechanical.Models.Enum;
using Microsoft.AspNetCore.Components.Routing;
using Newtonsoft.Json.Linq;

namespace mechanical.Services.AnnexService
{

    public class AnnexService : IAnnexService
    {
        public Task<double> GetMOVDepreciationRate(int serviceYear, BodyType bodyType)
        {
            var DepreciationRateAnnex = new Dictionary<int, Dictionary<BodyType, double>> {
                { 0, new Dictionary<BodyType, double>{{ BodyType.Compact, 1.000 },{ BodyType.Sedan, 1.000 },{ BodyType.StationWagon, 1.000 },{ BodyType.Pickup, 1.000 },{ BodyType.Minibus, 1.000 },{ BodyType.Bus, 1.000 },{ BodyType.TruckDryCargo, 1.000 },{ BodyType.TruckLiquidCargo, 1.000 }}},
                { 1, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.950 },{ BodyType.Sedan, 0.950 },{ BodyType.StationWagon, 0.955 },{ BodyType.Pickup, 0.945 },{ BodyType.Minibus, 0.957 },{ BodyType.Bus, 0.957 },{ BodyType.TruckDryCargo, 0.951 },{ BodyType.TruckLiquidCargo, 0.951 } }},
                { 2, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.903 },{ BodyType.Sedan, 0.903 },{ BodyType.StationWagon, 0.912 },{ BodyType.Pickup, 0.892 },{ BodyType.Minibus, 0.916 },{ BodyType.Bus, 0.916 },{ BodyType.TruckDryCargo, 0.904 },{ BodyType.TruckLiquidCargo, 0.904 } }},
                { 3, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.858 },{ BodyType.Sedan, 0.858 },{ BodyType.StationWagon, 0.870 },{ BodyType.Pickup, 0.843 },{ BodyType.Minibus, 0.877 },{ BodyType.Bus, 0.877 },{ BodyType.TruckDryCargo, 0.859 },{ BodyType.TruckLiquidCargo, 0.859 } }},
                { 4, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.815 },{ BodyType.Sedan, 0.815 },{ BodyType.StationWagon, 0.830 },{ BodyType.Pickup, 0.795 },{ BodyType.Minibus, 0.839 },{ BodyType.Bus, 0.839 },{ BodyType.TruckDryCargo, 0.816 },{ BodyType.TruckLiquidCargo, 0.816 } }},
                { 5, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.774 },{ BodyType.Sedan, 0.774 },{ BodyType.StationWagon, 0.792 },{ BodyType.Pickup, 0.750 },{ BodyType.Minibus, 0.802  },{ BodyType.Bus, 0.802 },{ BodyType.TruckDryCargo, 0.775},{ BodyType.TruckLiquidCargo, 0.775 } }},
                { 6, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.735 },{ BodyType.Sedan, 0.735 },{ BodyType.StationWagon, 0.755 },{ BodyType.Pickup, 0.707 },{ BodyType.Minibus, 0.767  },{ BodyType.Bus, 0.767 },{ BodyType.TruckDryCargo,  0.735 },{ BodyType.TruckLiquidCargo, 0.735 } }},
                { 7, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.697 },{ BodyType.Sedan, 0.697 },{ BodyType.StationWagon, 0.720 },{ BodyType.Pickup, 0.666 },{ BodyType.Minibus, 0.733  },{ BodyType.Bus, 0.733 },{ BodyType.TruckDryCargo,  0.697 },{ BodyType.TruckLiquidCargo, 0.697 } }},
                { 8, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.661 },{ BodyType.Sedan, 0.661 },{ BodyType.StationWagon, 0.686 },{ BodyType.Pickup, 0.627 },{ BodyType.Minibus, 0.700  },{ BodyType.Bus, 0.700 },{ BodyType.TruckDryCargo,  0.660 },{ BodyType.TruckLiquidCargo, 0.660 } }},
                { 9, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.627 },{ BodyType.Sedan, 0.627 },{ BodyType.StationWagon, 0.653 },{ BodyType.Pickup, 0.590 },{ BodyType.Minibus, 0.668  },{ BodyType.Bus, 0.668 },{ BodyType.TruckDryCargo,  0.625 },{ BodyType.TruckLiquidCargo, 0.625 } }},
                { 10, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.594 },{ BodyType.Sedan, 0.594 },{ BodyType.StationWagon, 0.622 },{ BodyType.Pickup, 0.554 },{ BodyType.Minibus, 0.637  },{ BodyType.Bus, 0.637 },{ BodyType.TruckDryCargo, 0.591 },{ BodyType.TruckLiquidCargo, 0.591 } }},
                { 11, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.562 },{ BodyType.Sedan, 0.562 },{ BodyType.StationWagon, 0.591 },{ BodyType.Pickup, 0.520 },{ BodyType.Minibus, 0.607  },{ BodyType.Bus, 0.607 },{ BodyType.TruckDryCargo, 0.558 },{ BodyType.TruckLiquidCargo, 0.558 } }},
                { 12, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.532 },{ BodyType.Sedan, 0.532 },{ BodyType.StationWagon, 0.562 },{ BodyType.Pickup, 0.486 },{ BodyType.Minibus, 0.579  },{ BodyType.Bus, 0.579 },{ BodyType.TruckDryCargo, 0.526 },{ BodyType.TruckLiquidCargo, 0.526 } }},
                { 13, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.502 },{ BodyType.Sedan, 0.502 },{ BodyType.StationWagon, 0.533 },{ BodyType.Pickup, 0.454 },{ BodyType.Minibus, 0.551  },{ BodyType.Bus, 0.551 },{ BodyType.TruckDryCargo, 0.495 },{ BodyType.TruckLiquidCargo, 0.495 } }},
                { 14, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.474 },{ BodyType.Sedan, 0.474 },{ BodyType.StationWagon, 0.505 },{ BodyType.Pickup, 0.424 },{ BodyType.Minibus, 0.523  },{ BodyType.Bus, 0.523 },{ BodyType.TruckDryCargo, 0.465 },{ BodyType.TruckLiquidCargo, 0.465 } }},
                { 15, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.446 },{ BodyType.Sedan, 0.446 },{ BodyType.StationWagon, 0.478 },{ BodyType.Pickup, 0.394 },{ BodyType.Minibus, 0.497  },{ BodyType.Bus, 0.497 },{ BodyType.TruckDryCargo, 0.436 },{ BodyType.TruckLiquidCargo, 0.436 } }},
                { 16, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.420 },{ BodyType.Sedan, 0.420 },{ BodyType.StationWagon, 0.452 },{ BodyType.Pickup, 0.365 },{ BodyType.Minibus, 0.471  },{ BodyType.Bus, 0.471 },{ BodyType.TruckDryCargo, 0.408 },{ BodyType.TruckLiquidCargo, 0.408 } }},
                { 17, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.394 },{ BodyType.Sedan, 0.394 },{ BodyType.StationWagon, 0.427 },{ BodyType.Pickup, 0.337 },{ BodyType.Minibus, 0.446  },{ BodyType.Bus, 0.446 },{ BodyType.TruckDryCargo, 0.381 },{ BodyType.TruckLiquidCargo, 0.381 } }},
                { 18, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.369 },{ BodyType.Sedan, 0.369 },{ BodyType.StationWagon, 0.402 },{ BodyType.Pickup, 0.310 },{ BodyType.Minibus, 0.422  },{ BodyType.Bus, 0.422 },{ BodyType.TruckDryCargo, 0.354 },{ BodyType.TruckLiquidCargo, 0.354 } }},
                { 19, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.345 },{ BodyType.Sedan, 0.345 },{ BodyType.StationWagon, 0.378 },{ BodyType.Pickup, 0.283 },{ BodyType.Minibus, 0.398  },{ BodyType.Bus, 0.398 },{ BodyType.TruckDryCargo, 0.328 },{ BodyType.TruckLiquidCargo, 0.328 } }},
                { 20, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.321 },{ BodyType.Sedan, 0.321 },{ BodyType.StationWagon, 0.355 },{ BodyType.Pickup, 0.258 },{ BodyType.Minibus, 0.375  },{ BodyType.Bus, 0.375 },{ BodyType.TruckDryCargo, 0.303 },{ BodyType.TruckLiquidCargo, 0.303 } }},
                { 21, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.298 },{ BodyType.Sedan, 0.298 },{ BodyType.StationWagon, 0.332 },{ BodyType.Pickup, 0.233 },{ BodyType.Minibus, 0.352  },{ BodyType.Bus, 0.352 },{ BodyType.TruckDryCargo, 0.278 },{ BodyType.TruckLiquidCargo, 0.278 } }},
                { 22, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.276 },{ BodyType.Sedan, 0.276 },{ BodyType.StationWagon, 0.310 },{ BodyType.Pickup, 0.208 },{ BodyType.Minibus, 0.330  },{ BodyType.Bus, 0.330 },{ BodyType.TruckDryCargo, 0.254 },{ BodyType.TruckLiquidCargo, 0.254 } }},
                { 23, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.254 },{ BodyType.Sedan, 0.254 },{ BodyType.StationWagon, 0.288 },{ BodyType.Pickup, 0.184 },{ BodyType.Minibus, 0.308  },{ BodyType.Bus, 0.308 },{ BodyType.TruckDryCargo, 0.230 },{ BodyType.TruckLiquidCargo, 0.207 } }},
                { 24, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.233 },{ BodyType.Sedan, 0.233 },{ BodyType.StationWagon, 0.267 },{ BodyType.Pickup, 0.161 },{ BodyType.Minibus, 0.287  },{ BodyType.Bus, 0.287 },{ BodyType.TruckDryCargo, 0.207 },{ BodyType.TruckLiquidCargo, 0.207 } }},
                { 25, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.212 },{ BodyType.Sedan, 0.212 },{ BodyType.StationWagon, 0.246 },{ BodyType.Pickup, 0.138 },{ BodyType.Minibus, 0.266  },{ BodyType.Bus, 0.266 },{ BodyType.TruckDryCargo, 0.184 },{ BodyType.TruckLiquidCargo, 0.184 } }},
                { 26, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.191 },{ BodyType.Sedan, 0.191 },{ BodyType.StationWagon, 0.225 },{ BodyType.Pickup, 0.116 },{ BodyType.Minibus, 0.246  },{ BodyType.Bus, 0.246 },{ BodyType.TruckDryCargo, 0.162 },{ BodyType.TruckLiquidCargo, 0.162 } }},
                { 27, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.171 },{ BodyType.Sedan, 0.171 },{ BodyType.StationWagon, 0.205 },{ BodyType.Pickup, 0.093 },{ BodyType.Minibus, 0.226  },{ BodyType.Bus, 0.226 },{ BodyType.TruckDryCargo, 0.140 },{ BodyType.TruckLiquidCargo, 0.140 } }},
                { 28, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.151 },{ BodyType.Sedan, 0.151 },{ BodyType.StationWagon, 0.185 },{ BodyType.Pickup, 0.072 },{ BodyType.Minibus, 0.206  },{ BodyType.Bus, 0.206 },{ BodyType.TruckDryCargo, 0.118 },{ BodyType.TruckLiquidCargo, 0.118 } }},
                { 29, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.132 },{ BodyType.Sedan, 0.132 },{ BodyType.StationWagon, 0.166 },{ BodyType.Pickup, 0.050 },{ BodyType.Minibus, 0.187  },{ BodyType.Bus, 0.187 },{ BodyType.TruckDryCargo, 0.097 },{ BodyType.TruckLiquidCargo, 0.097 } }},
                { 30, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.113 },{ BodyType.Sedan, 0.113 },{ BodyType.StationWagon, 0.147 },{ BodyType.Pickup, 0.029 },{ BodyType.Minibus, 0.168  },{ BodyType.Bus, 0.168 },{ BodyType.TruckDryCargo, 0.076 },{ BodyType.TruckLiquidCargo, 0.076 } }},
                { 31, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.094 },{ BodyType.Sedan, 0.094 },{ BodyType.StationWagon, 0.128 },{ BodyType.Pickup, 0.008 },{ BodyType.Minibus, 0.149  },{ BodyType.Bus, 0.149 },{ BodyType.TruckDryCargo, 0.055 },{ BodyType.TruckLiquidCargo, 0.055 } }},
                { 32, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.076 },{ BodyType.Sedan, 0.076 },{ BodyType.StationWagon, 0.110 },{ BodyType.Pickup, -0.012 },{ BodyType.Minibus, 0.131  },{ BodyType.Bus, 0.131 },{ BodyType.TruckDryCargo, 0.035 },{ BodyType.TruckLiquidCargo, 0.035 } }},
                { 33, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.058 },{ BodyType.Sedan, 0.058 },{ BodyType.StationWagon, 0.092 },{ BodyType.Pickup, -0.032 },{ BodyType.Minibus, 0.113  },{ BodyType.Bus, 0.113 },{ BodyType.TruckDryCargo, 0.015 },{ BodyType.TruckLiquidCargo, 0.015 } }},
                { 34, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.040 },{ BodyType.Sedan, 0.040 },{ BodyType.StationWagon, 0.074 },{ BodyType.Pickup, -0.052 },{ BodyType.Minibus, 0.095  },{ BodyType.Bus, 0.095 },{ BodyType.TruckDryCargo, -0.005 },{ BodyType.TruckLiquidCargo, -0.005 } }},
                { 35, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.022 },{ BodyType.Sedan, 0.022 },{ BodyType.StationWagon, 0.056 },{ BodyType.Pickup, -0.072 },{ BodyType.Minibus, 0.077  },{ BodyType.Bus, 0.077 },{ BodyType.TruckDryCargo, -0.024 },{ BodyType.TruckLiquidCargo, -0.024 } }},
                { 36, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.004 },{ BodyType.Sedan, 0.004 },{ BodyType.StationWagon, 0.038 },{ BodyType.Pickup, -0.092 },{ BodyType.Minibus, 0.060  },{ BodyType.Bus, 0.060 },{ BodyType.TruckDryCargo, -0.044 },{ BodyType.TruckLiquidCargo, -0.044 } }},
                { 37, new Dictionary<BodyType, double>{{ BodyType.Compact, -0.013 },{ BodyType.Sedan, -0.013 },{ BodyType.StationWagon, 0.021 },{ BodyType.Pickup, -0.111 },{ BodyType.Minibus, 0.042  },{ BodyType.Bus, 0.042 },{ BodyType.TruckDryCargo, -0.063 },{ BodyType.TruckLiquidCargo, -0.063 } }},
                { 38, new Dictionary<BodyType, double>{{ BodyType.Compact, -0.030 },{ BodyType.Sedan, -0.030 },{ BodyType.StationWagon, 0.004 },{ BodyType.Pickup, -0.130 },{ BodyType.Minibus, 0.025  },{ BodyType.Bus, 0.025 },{ BodyType.TruckDryCargo, -0.082 },{ BodyType.TruckLiquidCargo, -0.082 } }},
                { 39, new Dictionary<BodyType, double>{{ BodyType.Compact, -0.047 },{ BodyType.Sedan, -0.047 },{ BodyType.StationWagon, -0.013 },{ BodyType.Pickup, -0.150 },{ BodyType.Minibus, 0.008  },{ BodyType.Bus, 0.008 },{ BodyType.TruckDryCargo, -0.101 },{ BodyType.TruckLiquidCargo, -0.101 } }},
                { 40, new Dictionary<BodyType, double>{{ BodyType.Compact, -0.064 },{ BodyType.Sedan, -0.064 },{ BodyType.StationWagon, -0.030 },{ BodyType.Pickup, -0.169 },{ BodyType.Minibus, -0.008 },{ BodyType.Bus, -0.008 },{ BodyType.TruckDryCargo, -0.119 },{ BodyType.TruckLiquidCargo, -0.119 } }},

            };

            if (DepreciationRateAnnex.TryGetValue(serviceYear, out var bodyTypeDictionary))
            {
                if (bodyTypeDictionary.TryGetValue(bodyType, out var depreciationRate))
                {
                    return Task.FromResult(depreciationRate);
                }
            }
            throw new ArgumentException("Depreciation rate not found for the specified service year and body type.");
        }

        public Task<double> GetCAMDepreciationRate(int serviceYear, ConstructionMiningAgriculturalMachineryType bodyType)
        {
            var DepreciationRateAnnex = new Dictionary<int, Dictionary<ConstructionMiningAgriculturalMachineryType, double>> {
                { 0, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{{ ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 1.000 },{ ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 1.000 },{ ConstructionMiningAgriculturalMachineryType.Earthmoving, 1.000 },{ ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 1.000 }}},
                { 1, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{{ ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.945 },{ ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.956 },{ ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.948 },{ ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.958 } }},
                { 2, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{{ ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.894 },{ ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.913 },{ ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.899 },{ ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.917 } }},
                { 3, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{{ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.845 },{ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.872 },{ ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.852 },{ ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.878 }, }},
                { 4, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.798 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.833 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.807 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.841 } }},
                { 5, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.753 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.796 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.764 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.805 } }},
                { 6, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.711 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.759 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.722 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.770 } }},
                { 7, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.670 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.724 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.683 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.736 } }},
                { 8, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.631 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.691 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.645 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.704 } }},
                { 9, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.594 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.658 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.609 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.672 } }},
                { 10, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.558 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.627 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.574 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.641 } }},
                { 11, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.524 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.597 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.540 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.612 } }},
                { 12, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.491 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.567 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.508 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.583 } }},
                { 13, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.459 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.539 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.476 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.555 } }},
                { 14, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.428 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.511 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.446 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.528 } }},
                { 15, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.399 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.485 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.416 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.502 } }},
                { 16, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.370 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.459 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.388 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.476 } }},
                { 17, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.342 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.434 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.360 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.452 } }},
                { 18, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.315 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.409 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.333 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.427 } }},
                { 19, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.288 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.385 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.307 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.404 } }},
                { 20, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.263 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.362 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.281 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.381 } }},
                { 21, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.238 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.339 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.256 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.358 } }},
                { 22, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.213 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.317 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.232 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.336 } }},
                { 23, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.189 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.295 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.208 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.314 } }},
                { 24, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.166 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.274 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.185 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.293 } }},
                { 25, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.143 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.253 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.162 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.272 } }},
                { 26, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.121 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.232 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.140 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.252 } }},
                { 27, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.098 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.212 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.118 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.232 } }},
                { 28, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.077 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.192 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.096 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.212 } }},
                { 29, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.055 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.173 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.074 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.193 } }},
                { 30, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.034 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.154 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.053 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.174 } }},
                { 31, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, 0.013 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.135 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.033 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.155 } }},
                { 32, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, -0.007 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.117 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, 0.012 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.137 } }},
                { 33, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, -0.027 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.099 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, -0.008 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.119 } }},
                { 34, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, -0.047 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.081 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, -0.028 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.101 } }},
                { 35, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, -0.067 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.063 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, -0.047 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.083 } }},
                { 36, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, -0.087 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.045 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, -0.067 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.066 } }},
                { 37, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, -0.106 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.028 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, -0.086 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.048 } }},
                { 38, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, -0.125 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, 0.011 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, -0.105 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.031 } }},
                { 39, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, -0.144 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, -0.006 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, -0.124 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, 0.015 } }},
                { 40, new Dictionary<ConstructionMiningAgriculturalMachineryType, double>{ { ConstructionMiningAgriculturalMachineryType.CompactingConcretePumpCrusher, -0.163 }, { ConstructionMiningAgriculturalMachineryType.AgricultureLiftingDrilling, -0.023 }, { ConstructionMiningAgriculturalMachineryType.Earthmoving, -0.143 }, { ConstructionMiningAgriculturalMachineryType.RoadSurfaceFireFighting, -0.002 } }},

            };

            if (DepreciationRateAnnex.TryGetValue(serviceYear, out var bodyTypeDictionary))
            {
                if (bodyTypeDictionary.TryGetValue(bodyType, out var depreciationRate))
                {
                    return Task.FromResult(depreciationRate);
                }
            }
            throw new ArgumentException("Depreciation rate not found for the specified service year and body type.");
        }

        public Task<double> GetIBMDepreciationRate(int serviceYear, IndustrialBuildingMachineryType bodyType)
        {
            var DepreciationRateAnnex = new Dictionary<int, Dictionary<IndustrialBuildingMachineryType, double>> {
                { 0, new Dictionary<IndustrialBuildingMachineryType, double>{{ IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 1.000 },{ IndustrialBuildingMachineryType.HVACSecurityApparatus, 1.000 },{ IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 1.000 }}},
                { 1, new Dictionary<IndustrialBuildingMachineryType, double>{{ IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.965 },{ IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.937 },{ IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.890 } }},
                { 2, new Dictionary<IndustrialBuildingMachineryType, double>{{ IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.931 },{ IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.878 },{ IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.792 } }},
                { 3, new Dictionary<IndustrialBuildingMachineryType, double>{{IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.898 },{IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.823 },{ IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.705 } }},
                { 4, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.867 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.771 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.627 } }},
                { 5, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.836 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.722 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.557 } }},
                { 6, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.806 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.676 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.492 } }},
                { 7, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.778 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.632 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.433 } }},
                { 8, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.750 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.591 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.379 } }},
                { 9, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.723 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.551 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.328 } }},
                { 10, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.696 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.514 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.281 } }},
                { 11, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.671 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.478 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.236 } }},
                { 12, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.646 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.444 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.193 } }},
                { 13, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.622 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.412 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.152 } }},
                { 14, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.598 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.380 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.113 } }},
                { 15, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.575 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.350 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.175 } }},
                { 16, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.553 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.321 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.038 } }},
                { 17, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.531 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.293 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, 0.002 } }},
                { 18, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.510 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.266 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.033 } }},
                { 19, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.490 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.240 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.067 } }},
                { 20, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.469 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.214 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.101 } }},
                { 21, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.450 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.189 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.134 } }},
                { 22, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.430 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.165 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment,-0.167 } }},
                { 23, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.411 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.141 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.200 } }},
                { 24, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.393 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.118 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.232 } }},
                { 25, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.375 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.095 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.264 } }},
                { 26, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.357 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.073 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.296 } }},
                { 27, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.339 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.051 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.328 } }},
                { 28, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.322 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.029 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.359 } }},
                { 29, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.305 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, 0.008 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.391 } }},
                { 30, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.289 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, -0.013 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.422 } }},
                { 31, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.273 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, -0.034 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.453 } }},
                { 32, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.257 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, -0.055 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.485 } }},
                { 33, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.241 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, -0.075 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.516 } }},
                { 34, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.226 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, -0.095 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.547 } }},
                { 35, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.210 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, -0.115 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.578 } }},
                { 36, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.195 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, -0.135 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.609 } }},
                { 37, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.180 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, -0.154 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.640 } }},
                { 38, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.166 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, -0.174 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.671 } }},
                { 39, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.151 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, -0.193 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.702 } }},
                { 40, new Dictionary<IndustrialBuildingMachineryType, double>{ { IndustrialBuildingMachineryType.IndustrialProcessLineEquipment, 0.137 }, { IndustrialBuildingMachineryType.HVACSecurityApparatus, -0.212 }, { IndustrialBuildingMachineryType.HotelOfficeLaboratoryEquipment, -0.733 } }},

            };

            if (DepreciationRateAnnex.TryGetValue(serviceYear, out var bodyTypeDictionary))
            {
                if (bodyTypeDictionary.TryGetValue(bodyType, out var depreciationRate))
                {
                    return Task.FromResult(depreciationRate);
                }
            }
            throw new ArgumentException("Depreciation rate not found for the specified service year and body type.");
        }

        public Task<double> GetMOVMarketShareFactor(MotorVehicleMake motorVehicleMake, BodyType bodyType)
        {
            var MarketShareFactorAnnex = new Dictionary<MotorVehicleMake, Dictionary<BodyType, double>> {
                { MotorVehicleMake.Acya, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.95 },{ BodyType.TruckLiquidCargo, 0.95 } } },
                { MotorVehicleMake.Astra, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 1.10 },{ BodyType.TruckLiquidCargo, 1.10 } }},
                { MotorVehicleMake.Audi, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.90 },{ BodyType.Sedan, 0.90 },{ BodyType.StationWagon, 0.90 },{ BodyType.Pickup, 0.90 },{ BodyType.Minibus, 0.90 },{ BodyType.Bus, 0.90 },{ BodyType.TruckDryCargo, 0.90 },{ BodyType.TruckLiquidCargo, 0.90 } }},
                { MotorVehicleMake.BMW, new Dictionary<BodyType, double>{{ BodyType.Compact, 1.10 },{ BodyType.Sedan, 1.10 },{ BodyType.StationWagon, 1.10 },{ BodyType.Pickup, 1.00 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.95 },{ BodyType.TruckLiquidCargo, 0.95 } }},
                { MotorVehicleMake.Chevrolet, new Dictionary<BodyType, double>{{ BodyType.Compact, 1.10 },{ BodyType.Sedan, 1.10 },{ BodyType.StationWagon, 1.10 },{ BodyType.Pickup, 1.10 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.95 },{ BodyType.TruckLiquidCargo, 0.95 } }},
                { MotorVehicleMake.Dachia, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.95 },{ BodyType.TruckLiquidCargo, 0.95 } }},
                { MotorVehicleMake.DAF, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 1.10 },{ BodyType.TruckLiquidCargo, 1.10 } }},
                { MotorVehicleMake.FiatIveco, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 1.00 },{ BodyType.Pickup, 1.00 },{ BodyType.Minibus, 1.10 },{ BodyType.Bus, 1.10 },{ BodyType.TruckDryCargo, 1.10 },{ BodyType.TruckLiquidCargo, 1.10 } }},
                { MotorVehicleMake.Ford, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.80 },{ BodyType.Sedan, 0.80 },{ BodyType.StationWagon, 0.80 },{ BodyType.Pickup, 0.80 },{ BodyType.Minibus, 0.80 },{ BodyType.Bus, 0.80 },{ BodyType.TruckDryCargo, 0.80 },{ BodyType.TruckLiquidCargo, 0.80 } }},
                { MotorVehicleMake.Gevang, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.95 },{ BodyType.TruckLiquidCargo, 0.95 } }},
                { MotorVehicleMake.Hino, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.80 },{ BodyType.Sedan, 0.80 },{ BodyType.StationWagon, 0.80 },{ BodyType.Pickup, 0.80 },{ BodyType.Minibus, 0.80 },{ BodyType.Bus, 0.80 },{ BodyType.TruckDryCargo, 1.00 },{ BodyType.TruckLiquidCargo, 1.00 } }},
                { MotorVehicleMake.Honda, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.80 },{ BodyType.TruckLiquidCargo, 0.80 } }},
                { MotorVehicleMake.Hyunda, new Dictionary<BodyType, double>{{ BodyType.Compact, 1.10 },{ BodyType.Sedan, 1.10 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.95 },{ BodyType.TruckLiquidCargo, 0.95 } }},
                { MotorVehicleMake.International, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.90 },{ BodyType.Sedan, 0.90 },{ BodyType.StationWagon, 0.90 },{ BodyType.Pickup, 0.90 },{ BodyType.Minibus, 0.90 },{ BodyType.Bus, 0.90 },{ BodyType.TruckDryCargo, 1.10 },{ BodyType.TruckLiquidCargo, 1.10 } }},
                { MotorVehicleMake.Isuzu, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.90 },{ BodyType.Pickup, 0.90 },{ BodyType.Minibus, 1.10 },{ BodyType.Bus, 1.10 },{ BodyType.TruckDryCargo, 1.10 },{ BodyType.TruckLiquidCargo, 1.10 } }},
                { MotorVehicleMake.Kamaz, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.80 },{ BodyType.Sedan, 0.80 },{ BodyType.StationWagon, 0.80 },{ BodyType.Pickup, 0.80 },{ BodyType.Minibus, 0.80 },{ BodyType.Bus, 0.80 },{ BodyType.TruckDryCargo, 0.80 },{ BodyType.TruckLiquidCargo, 0.80 } }},
                { MotorVehicleMake.Kia, new Dictionary<BodyType, double>{{ BodyType.Compact, 1.10 },{ BodyType.Sedan, 1.10 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 1.00 },{ BodyType.TruckLiquidCargo, 1.00 } }},
                { MotorVehicleMake.Lada, new Dictionary<BodyType, double>{{ BodyType.Compact, 1.00 },{ BodyType.Sedan, 1.00 },{ BodyType.StationWagon, 0.80 },{ BodyType.Pickup, 0.80 },{ BodyType.Minibus, 0.80 },{ BodyType.Bus, 0.80 },{ BodyType.TruckDryCargo, 0.80 },{ BodyType.TruckLiquidCargo, 0.80 } }},
                { MotorVehicleMake.LandRover, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.95 },{ BodyType.TruckLiquidCargo, 0.95 } }},
                { MotorVehicleMake.Mack, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 1.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 1.10 },{ BodyType.TruckLiquidCargo, 1.10 } }},
                { MotorVehicleMake.Mazda, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 1.00 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.95 },{ BodyType.TruckLiquidCargo, 0.95 } }},
                { MotorVehicleMake.Mercedes, new Dictionary<BodyType, double>{{ BodyType.Compact, 1.05 },{ BodyType.Sedan, 1.05 },{ BodyType.StationWagon, 1.05 },{ BodyType.Pickup, 1.05 },{ BodyType.Minibus, 1.05 },{ BodyType.Bus, 1.05 },{ BodyType.TruckDryCargo, 1.10 },{ BodyType.TruckLiquidCargo, 1.10 } }},
                { MotorVehicleMake.Mitsubishi, new Dictionary<BodyType, double>{{ BodyType.Compact, 1.10 },{ BodyType.Sedan, 1.10 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 1.10 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 1.00 },{ BodyType.TruckLiquidCargo, 1.00 } }},
                { MotorVehicleMake.Nissan, new Dictionary<BodyType, double>{{ BodyType.Compact, 1.05 },{ BodyType.Sedan, 1.05 },{ BodyType.StationWagon, 1.10 },{ BodyType.Pickup, 1.10 },{ BodyType.Minibus, 1.10 },{ BodyType.Bus, 1.10 },{ BodyType.TruckDryCargo, 1.10 },{ BodyType.TruckLiquidCargo, 1.10 } }},
                { MotorVehicleMake.Niva, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.80 },{ BodyType.Sedan, 0.80 },{ BodyType.StationWagon, 0.80 },{ BodyType.Pickup, 0.80 },{ BodyType.Minibus, 0.80 },{ BodyType.Bus, 0.80 },{ BodyType.TruckDryCargo, 0.80 },{ BodyType.TruckLiquidCargo, 0.80 } }},
                { MotorVehicleMake.Opel, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.95 },{ BodyType.TruckLiquidCargo, 0.95 } }},
                { MotorVehicleMake.Others, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.80 },{ BodyType.Sedan, 0.80 },{ BodyType.StationWagon, 0.80 },{ BodyType.Pickup, 0.80 },{ BodyType.Minibus, 0.80 },{ BodyType.Bus, 0.80 },{ BodyType.TruckDryCargo, 0.80 },{ BodyType.TruckLiquidCargo, 0.80 } }},
                { MotorVehicleMake.Peugeot, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.80 },{ BodyType.Sedan, 0.80 },{ BodyType.StationWagon, 0.80 },{ BodyType.Pickup, 0.80 },{ BodyType.Minibus, 0.80 },{ BodyType.Bus, 0.80 },{ BodyType.TruckDryCargo, 0.80 },{ BodyType.TruckLiquidCargo, 0.80 } }},
                { MotorVehicleMake.Raf, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.95 },{ BodyType.TruckLiquidCargo, 0.95 } }},
                { MotorVehicleMake.RangeRover, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 1.10 },{ BodyType.Pickup, 1.00 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.95 },{ BodyType.TruckLiquidCargo, 0.95 } }},
                { MotorVehicleMake.Renault, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 1.00 },{ BodyType.TruckLiquidCargo, 1.00 } }},
                { MotorVehicleMake.Scania, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.80 },{ BodyType.Sedan, 0.80 },{ BodyType.StationWagon, 0.80 },{ BodyType.Pickup, 0.80 },{ BodyType.Minibus, 0.80 },{ BodyType.Bus, 0.80 },{ BodyType.TruckDryCargo, 1.10 },{ BodyType.TruckLiquidCargo, 1.10 } }},
                { MotorVehicleMake.Sino, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.80 },{ BodyType.Sedan, 0.80 },{ BodyType.StationWagon, 0.90 },{ BodyType.Pickup, 0.90 },{ BodyType.Minibus, 1.00 },{ BodyType.Bus, 1.00 },{ BodyType.TruckDryCargo, 1.00 },{ BodyType.TruckLiquidCargo, 1.00 } }},
                { MotorVehicleMake.Suzuki, new Dictionary<BodyType, double>{{ BodyType.Compact, 1.05 },{ BodyType.Sedan, 1.05 },{ BodyType.StationWagon, 1.05 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.80 },{ BodyType.TruckLiquidCargo, 0.80 } }},
                { MotorVehicleMake.Tata, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 1.00 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.95 },{ BodyType.TruckLiquidCargo, 0.95 } }},
                { MotorVehicleMake.Toyota, new Dictionary<BodyType, double>{{ BodyType.Compact, 1.10 },{ BodyType.Sedan, 1.10 },{ BodyType.StationWagon, 1.10 },{ BodyType.Pickup, 1.10 },{ BodyType.Minibus, 1.10 },{ BodyType.Bus, 1.10 },{ BodyType.TruckDryCargo, 0.80 },{ BodyType.TruckLiquidCargo, 0.80 } }},
                { MotorVehicleMake.Volkswagen, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 0.80 },{ BodyType.TruckLiquidCargo, 0.80 } }},
                { MotorVehicleMake.Volvo, new Dictionary<BodyType, double>{{ BodyType.Compact, 0.95 },{ BodyType.Sedan, 0.95 },{ BodyType.StationWagon, 0.95 },{ BodyType.Pickup, 0.95 },{ BodyType.Minibus, 0.95 },{ BodyType.Bus, 0.95 },{ BodyType.TruckDryCargo, 1.10 },{ BodyType.TruckLiquidCargo, 1.10 } }},
            };
            if (MarketShareFactorAnnex.TryGetValue(motorVehicleMake, out var bodyTypeDictionary))
            {
                if (bodyTypeDictionary.TryGetValue(bodyType, out var marketShareFactor))
                {
                    return Task.FromResult(marketShareFactor);
                }
            }
            throw new ArgumentException("Market Share Factor not found for the specified service year and body type.");
        }

        public Task<double> GetEquipmentConditionFactor(EquipmentCondition equipmentCondition, AllocatedPointRange allocatedPointRange)
        {
            var EquipmentConditionFactorAnnex = new Dictionary<EquipmentCondition, Dictionary<AllocatedPointRange, double>> {
                 { EquipmentCondition.New, new Dictionary<AllocatedPointRange, double>{{ AllocatedPointRange.First, 1.00 },{ AllocatedPointRange.Second, 1.00 },{ AllocatedPointRange.Third, 1.00 },{ AllocatedPointRange.Fourth, 1.00 }, { AllocatedPointRange.Fifth, 1.00 }, { AllocatedPointRange.Sixth, 1.00 }, { AllocatedPointRange.Seventh, 1.00 }, { AllocatedPointRange.Eighth, 1.00 }, { AllocatedPointRange.Ninth, 1.00 }, { AllocatedPointRange.Tenth, 1.00 }, { AllocatedPointRange.Eleventh, 1.00 }, { AllocatedPointRange.Twelfth, 1.00 }, { AllocatedPointRange.Thirteenth, 1.00 }, { AllocatedPointRange.Fourteenth, 1.00 }, { AllocatedPointRange.Fifteenth, 1.00 }, { AllocatedPointRange.Sixteenth, 1.00 }, { AllocatedPointRange.Seventeenth, 1.00 }, { AllocatedPointRange.Eighteenth, 1.00 }, { AllocatedPointRange.Nineteenth, 1.00 }, { AllocatedPointRange.Twentieth, 1.00 } } },
                 { EquipmentCondition.FunctionalWithOverhaul, new Dictionary<AllocatedPointRange, double>{{ AllocatedPointRange.First, 0.87 },{ AllocatedPointRange.Second, 0.88 },{ AllocatedPointRange.Third, 0.89 },{ AllocatedPointRange.Fourth, 0.90 }, { AllocatedPointRange.Fifth, 0.91 }, { AllocatedPointRange.Sixth, 0.92 }, { AllocatedPointRange.Seventh, 0.93 }, { AllocatedPointRange.Eighth, 0.94 }, { AllocatedPointRange.Ninth, 0.95 }, { AllocatedPointRange.Tenth, 0.96 }, { AllocatedPointRange.Eleventh, 0.97 }, { AllocatedPointRange.Twelfth, 0.98 }, { AllocatedPointRange.Thirteenth, 0.99 }, { AllocatedPointRange.Fourteenth, 0.99 }, { AllocatedPointRange.Fifteenth, 0.99 }, { AllocatedPointRange.Sixteenth, 0.99 }, { AllocatedPointRange.Seventeenth, 0.99 }, { AllocatedPointRange.Eighteenth, 0.99 }, { AllocatedPointRange.Nineteenth, 0.99 }, { AllocatedPointRange.Twentieth, 0.99 } } },
                 { EquipmentCondition.FunctionalWithoutOverhaul, new Dictionary<AllocatedPointRange, double>{{ AllocatedPointRange.First, 0.75 },{ AllocatedPointRange.Second, 0.76 },{ AllocatedPointRange.Third, 0.77 },{ AllocatedPointRange.Fourth, 0.78 }, { AllocatedPointRange.Fifth, 0.79 }, { AllocatedPointRange.Sixth, 0.80 }, { AllocatedPointRange.Seventh, 0.81 }, { AllocatedPointRange.Eighth, 0.82 }, { AllocatedPointRange.Ninth, 0.83 }, { AllocatedPointRange.Tenth, 0.84 }, { AllocatedPointRange.Eleventh, 0.85 }, { AllocatedPointRange.Twelfth, 0.86 }, { AllocatedPointRange.Thirteenth, 0.86 }, { AllocatedPointRange.Fourteenth, 0.86 }, { AllocatedPointRange.Fifteenth, 0.86 }, { AllocatedPointRange.Sixteenth, 0.86 }, { AllocatedPointRange.Seventeenth, 0.86 }, { AllocatedPointRange.Eighteenth, 0.86 }, { AllocatedPointRange.Nineteenth, 0.86 }, { AllocatedPointRange.Twentieth, 0.86 } } },
                 { EquipmentCondition.NotFunctionalMinorRepair, new Dictionary<AllocatedPointRange, double>{{ AllocatedPointRange.First, 0.62 },{ AllocatedPointRange.Second, 0.63 },{ AllocatedPointRange.Third, 0.64 },{ AllocatedPointRange.Fourth, 0.65 }, { AllocatedPointRange.Fifth, 0.66 }, { AllocatedPointRange.Sixth, 0.67 }, { AllocatedPointRange.Seventh, 0.68 }, { AllocatedPointRange.Eighth, 0.69 }, { AllocatedPointRange.Ninth, 0.70 }, { AllocatedPointRange.Tenth, 0.71 }, { AllocatedPointRange.Eleventh, 0.72 }, { AllocatedPointRange.Twelfth, 0.73 }, { AllocatedPointRange.Thirteenth, 0.74 }, { AllocatedPointRange.Fourteenth, 0.74 }, { AllocatedPointRange.Fifteenth, 0.74 }, { AllocatedPointRange.Sixteenth, 0.74 }, { AllocatedPointRange.Seventeenth, 0.74 }, { AllocatedPointRange.Eighteenth, 0.74 }, { AllocatedPointRange.Nineteenth, 0.74 }, { AllocatedPointRange.Twentieth, 0.74 } } },
                 { EquipmentCondition.NotFunctionalMediumRepair, new Dictionary<AllocatedPointRange, double>{{ AllocatedPointRange.First, 0.50 },{ AllocatedPointRange.Second, 0.51 },{ AllocatedPointRange.Third, 0.52 },{ AllocatedPointRange.Fourth, 0.53 }, { AllocatedPointRange.Fifth, 0.54 }, { AllocatedPointRange.Sixth, 0.55 }, { AllocatedPointRange.Seventh, 0.56 }, { AllocatedPointRange.Eighth, 0.57 }, { AllocatedPointRange.Ninth, 0.58 }, { AllocatedPointRange.Tenth, 0.59 }, { AllocatedPointRange.Eleventh, 0.60 }, { AllocatedPointRange.Twelfth, 0.61 }, { AllocatedPointRange.Thirteenth, 0.61 }, { AllocatedPointRange.Fourteenth, 0.61 }, { AllocatedPointRange.Fifteenth, 0.61 }, { AllocatedPointRange.Sixteenth, 0.61 }, { AllocatedPointRange.Seventeenth, 0.61 }, { AllocatedPointRange.Eighteenth, 0.61 }, { AllocatedPointRange.Nineteenth, 0.61 }, { AllocatedPointRange.Twentieth, 0.61 } } },
                 { EquipmentCondition.NotOperationalMinorPartsMissing, new Dictionary<AllocatedPointRange, double>{{ AllocatedPointRange.First, 0.30 },{ AllocatedPointRange.Second, 0.31 },{ AllocatedPointRange.Third, 0.32 },{ AllocatedPointRange.Fourth, 0.33 }, { AllocatedPointRange.Fifth, 0.34 }, { AllocatedPointRange.Sixth, 0.35 }, { AllocatedPointRange.Seventh, 0.36 }, { AllocatedPointRange.Eighth, 0.37 }, { AllocatedPointRange.Ninth, 0.38 }, { AllocatedPointRange.Tenth, 0.39 }, { AllocatedPointRange.Eleventh, 0.40 }, { AllocatedPointRange.Twelfth, 0.41 }, { AllocatedPointRange.Thirteenth, 0.42 }, { AllocatedPointRange.Fourteenth, 0.43 }, { AllocatedPointRange.Fifteenth, 0.44 }, { AllocatedPointRange.Sixteenth, 0.45 }, { AllocatedPointRange.Seventeenth, 0.46 }, { AllocatedPointRange.Eighteenth, 0.47 }, { AllocatedPointRange.Nineteenth, 0.48 }, { AllocatedPointRange.Twentieth, 0.49 } } },
                 { EquipmentCondition.NotOperationalMajorComponentsMissing, new Dictionary<AllocatedPointRange, double>{{ AllocatedPointRange.First, 0.10 },{ AllocatedPointRange.Second, 0.11 },{ AllocatedPointRange.Third, 0.12 },{ AllocatedPointRange.Fourth, 0.13 }, { AllocatedPointRange.Fifth, 0.14 }, { AllocatedPointRange.Sixth, 0.15 }, { AllocatedPointRange.Seventh, 0.16 }, { AllocatedPointRange.Eighth, 0.17 }, { AllocatedPointRange.Ninth, 0.18 }, { AllocatedPointRange.Tenth, 0.19 }, { AllocatedPointRange.Eleventh, 0.20 }, { AllocatedPointRange.Twelfth, 0.21 }, { AllocatedPointRange.Thirteenth, 0.22 }, { AllocatedPointRange.Fourteenth, 0.23 }, { AllocatedPointRange.Fifteenth, 0.24 }, { AllocatedPointRange.Sixteenth, 0.25 }, { AllocatedPointRange.Seventeenth, 0.26 }, { AllocatedPointRange.Eighteenth, 0.27 }, { AllocatedPointRange.Nineteenth, 0.28 }, { AllocatedPointRange.Twentieth, 0.29 } } },
            };
            if (EquipmentConditionFactorAnnex.TryGetValue(equipmentCondition, out var allocatedPointRangeDictonary))
            {
                if (allocatedPointRangeDictonary.TryGetValue(allocatedPointRange, out var equipmentConditonFactor))
                {
                    return Task.FromResult(equipmentConditonFactor);
                }
            }
            throw new ArgumentException("Equipment Condition Factor not found for the specified service year and body type.");
        }




        public Task<double> GetCAMIBFMarketShareFactor(MachineryTechnologyStandard machineryTechnologyStandard)
        {
            var MarketShareFactorAnnex = new Dictionary<MachineryTechnologyStandard, double> {
                { MachineryTechnologyStandard.WesternEurope,1.00 },
                { MachineryTechnologyStandard.EasternEurope,0.8 },
                { MachineryTechnologyStandard.NorthAmerica,1.00 },
                { MachineryTechnologyStandard.SouthAmerica,0.8 },
                { MachineryTechnologyStandard.Asia,0.9 },
                { MachineryTechnologyStandard.Australia,0.8 },
                { MachineryTechnologyStandard.Antarctica,0.9 },
                { MachineryTechnologyStandard.Africa,0.8 },
                { MachineryTechnologyStandard.JapanStandard,1.00 },
                { MachineryTechnologyStandard.ChinaEuropeanAmericanStandard,1.00 },
                { MachineryTechnologyStandard.BrazilCoffeeProcessing,1.00 }
            };
            if (MarketShareFactorAnnex.TryGetValue(machineryTechnologyStandard, out var bodyTypeDictionary))
            {
                return Task.FromResult(bodyTypeDictionary);

            }
            throw new ArgumentException("Market Share Factor not found for the specified service year and body type.");
        }
    }
}